# (SELECT AO.ANIMAL_ID 
# FROM ANIMAL_INS AI INNER JOIN ANIMAL_OUTS AO 
# ON AI.ANIMAL_ID = AO.ANIMAL_ID;) -- 있는거

# SELECT AO.ANIMAL_ID, AO.NAME
# FROM ANIMAL_OUTS AO
# WHERE AO.ANIMAL_ID NOT IN (SELECT AO.ANIMAL_ID
# FROM ANIMAL_INS AI INNER JOIN ANIMAL_OUTS AO 
# ON AI.ANIMAL_ID = AO.ANIMAL_ID);

# SELECT AO.ANIMAL_ID, AO.NAME
# FROM ANIMAL_OUTS AO LEFT JOIN ANIMAL_INS AI
# ON AO.ANIMAL_ID = AI.ANIMAL_ID
# WHERE AI.ANIMAL_ID IS NULL; 

SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AO
WHERE AO.ANIMAL_ID NOT IN(SELECT ANIMAL_ID FROM ANIMAL_INS); 
-- NULL이 포함 될 경우 문법적 문제 발생 가능 문제 발생 가능
