-- 코드를 입력하세요
# (SELECT AO.ANIMAL_ID, AO.NAME 
# FROM ANIMAL_INS AI INNER JOIN ANIMAL_OUTS AO 
# ON AI.ANIMAL_ID = AO.ANIMAL_ID;) -- 있는거

SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AO
WHERE AO.ANIMAL_ID NOT IN (SELECT AO.ANIMAL_ID
FROM ANIMAL_INS AI INNER JOIN ANIMAL_OUTS AO 
ON AI.ANIMAL_ID = AO.ANIMAL_ID);