SELECT UGS.USER_ID, UGS.NICKNAME, SUM(UGB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UGB
INNER JOIN USED_GOODS_USER UGS 
ON UGB.WRITER_ID = UGS.USER_ID
WHERE UGB.STATUS = 'DONE'
GROUP BY UGB.WRITER_ID
HAVING SUM(UGB.PRICE) >=700000
ORDER BY TOTAL_SALES;